-- PEXVORO project intake schema
-- Review in Supabase SQL Editor before running. Creates only the leads table.
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  business text not null,
  email text not null,
  business_type text not null default '',
  problem text not null default '',
  current_software text not null default '',
  contact text not null default 'Email',
  automation text not null default '',
  budget text not null default 'Just exploring',
  package text not null default 'Not sure yet',
  description text not null,
  consent boolean not null default false,
  status text not null default 'new' check (status in ('new', 'reviewing', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

-- Do not add public/anon SELECT, INSERT, UPDATE, or DELETE policies.
-- The server endpoint uses SUPABASE_SERVICE_ROLE_KEY, which must only exist
-- in server-side Vercel environment variables and must never be sent to browsers.
